config:
  credentials: []
  project_repos:
    git.man.poznan.pl/stash/scm/eosc-rs/rs-facade:
      branch: master
      repo: https://git.man.poznan.pl/stash/scm/eosc-rs/rs-facade.git
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.11
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      git.man.poznan.pl/stash/scm/eosc-rs/rs-facade git:
        commands:
        - /usr/bin/env sh .sqa/script.stealthy-goldenrod-markhor.sh
        container: qc.acc_woozy-celadon-mayfly
  QC.Doc:
    repos:
      git.man.poznan.pl/stash/scm/eosc-rs/rs-facade find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.tacky-periwinkle-kangaroo.sh
        container: qc.doc_lousy-chestnut-dunker
      git.man.poznan.pl/stash/scm/eosc-rs/rs-facade git:
        commands:
        - /usr/bin/env sh .sqa/script.skanky-platinum-urchin.sh
        container: qc.doc_bumpy-magnolia-cuttlefish
      git.man.poznan.pl/stash/scm/eosc-rs/rs-facade markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.droopy-periwinkle-coati.sh
        container: qc.doc_seedy-dandelion-eleuth
  QC.Lic:
    repos:
      git.man.poznan.pl/stash/scm/eosc-rs/rs-facade licensee:
        commands:
        - /usr/bin/env sh .sqa/script.boozy-eggplant-havanese.sh
        container: qc.lic_gummy-denim-corgi
  QC.Met:
    repos:
      git.man.poznan.pl/stash/scm/eosc-rs/rs-facade cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.chummy-beige-owl.sh
        container: qc.met_shabby-rose-gecko
  QC.Sec:
    repos:
      git.man.poznan.pl/stash/scm/eosc-rs/rs-facade bandit:
        commands:
        - /usr/bin/env sh .sqa/script.beady-sapphire-hyena.sh
        container: qc.sec_woolly-plum-affenpinscher
  QC.Sty:
    repos:
      git.man.poznan.pl/stash/scm/eosc-rs/rs-facade flake8:
        commands:
        - /usr/bin/env sh .sqa/script.wimpy-flax-dachshund.sh
        container: qc.sty_messy-bistre-tuatara
      git.man.poznan.pl/stash/scm/eosc-rs/rs-facade hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.gimpy-chartreuse-cuttlefish.sh
        container: qc.sty_cheeky-celadon-whale
      git.man.poznan.pl/stash/scm/eosc-rs/rs-facade jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.crabby-tan-caiman.sh
        container: qc.sty_goopy-malachite-pinscher
  QC.Ver:
    repos:
      git.man.poznan.pl/stash/scm/eosc-rs/rs-facade get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.clammy-aquamarine-butterfly.sh
        container: qc.ver_sunny-gold-birman
timeout: 5400
