config:
  credentials: []
  project_repos:
    git.man.poznan.pl/stash/scm/eosc-rs/rs-facade:
      branch: master
      repo: https://git.man.poznan.pl/stash/scm/eosc-rs/rs-facade.git
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.9
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      git.man.poznan.pl/stash/scm/eosc-rs/rs-facade git:
        commands:
        - /usr/bin/env sh .sqa/script.crabby-heliotrope-gharial.sh
        container: qc.acc_slaphappy-rose-cichlid
  QC.Doc:
    repos:
      git.man.poznan.pl/stash/scm/eosc-rs/rs-facade find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.silly-dandelion-chicken.sh
        container: qc.doc_snippy-thistle-hedgehog
      git.man.poznan.pl/stash/scm/eosc-rs/rs-facade git:
        commands:
        - /usr/bin/env sh .sqa/script.sleepy-grey-turkey.sh
        container: qc.doc_grumpy-lavender-penguin
      git.man.poznan.pl/stash/scm/eosc-rs/rs-facade markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.snazzy-carmine-gecko.sh
        container: qc.doc_nerdy-tangerine-eel
  QC.Lic:
    repos:
      git.man.poznan.pl/stash/scm/eosc-rs/rs-facade licensee:
        commands:
        - /usr/bin/env sh .sqa/script.sleazy-smalt-angelfish.sh
        container: qc.lic_randy-green-eleuth
  QC.Met:
    repos:
      git.man.poznan.pl/stash/scm/eosc-rs/rs-facade cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.blurry-cornflower-jellyfish.sh
        container: qc.met_scaly-jade-lizard
  QC.Sec:
    repos:
      git.man.poznan.pl/stash/scm/eosc-rs/rs-facade bandit:
        commands:
        - /usr/bin/env sh .sqa/script.lovely-sangria-booby.sh
        container: qc.sec_cloudy-rust-terrier
  QC.Sty:
    repos:
      git.man.poznan.pl/stash/scm/eosc-rs/rs-facade flake8:
        commands:
        - /usr/bin/env sh .sqa/script.squeaky-chestnut-kudu.sh
        container: qc.sty_stealthy-blue-elephant
      git.man.poznan.pl/stash/scm/eosc-rs/rs-facade hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.gamy-burgundy-centipede.sh
        container: qc.sty_muzzy-mauve-crane
      git.man.poznan.pl/stash/scm/eosc-rs/rs-facade jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.ready-indigo-maltese.sh
        container: qc.sty_ready-charcoal-ostrich
  QC.Ver:
    repos:
      git.man.poznan.pl/stash/scm/eosc-rs/rs-facade get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.seedy-crimson-seal.sh
        container: qc.ver_nippy-cream-lemur
timeout: 5400
