config:
  credentials: []
  project_repos:
    git.man.poznan.pl/stash/scm/eosc-rs/rs-facade:
      branch: master
      repo: https://git.man.poznan.pl/stash/scm/eosc-rs/rs-facade.git
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.9
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      git.man.poznan.pl/stash/scm/eosc-rs/rs-facade git:
        commands:
        - /usr/bin/env sh .sqa/script.lanky-zucchini-sheepdog.sh
        container: qc.acc_hilly-violet-catfish
  QC.Doc:
    repos:
      git.man.poznan.pl/stash/scm/eosc-rs/rs-facade find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.crappy-malachite-markhor.sh
        container: qc.doc_zippy-cream-terrier
      git.man.poznan.pl/stash/scm/eosc-rs/rs-facade git:
        commands:
        - /usr/bin/env sh .sqa/script.squirrely-zucchini-toucan.sh
        container: qc.doc_pokey-sepia-dragonfly
      git.man.poznan.pl/stash/scm/eosc-rs/rs-facade markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.stinky-orange-falcon.sh
        container: qc.doc_boozy-chartreuse-toucan
  QC.Lic:
    repos:
      git.man.poznan.pl/stash/scm/eosc-rs/rs-facade licensee:
        commands:
        - /usr/bin/env sh .sqa/script.homey-denim-koala.sh
        container: qc.lic_goopy-auburn-olm
  QC.Met:
    repos:
      git.man.poznan.pl/stash/scm/eosc-rs/rs-facade cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.slaphappy-olivine-zebu.sh
        container: qc.met_crabby-platinum-mayfly
  QC.Sec:
    repos:
      git.man.poznan.pl/stash/scm/eosc-rs/rs-facade bandit:
        commands:
        - /usr/bin/env sh .sqa/script.flimsy-white-tapir.sh
        container: qc.sec_stinky-zucchini-wolfhound
  QC.Sty:
    repos:
      git.man.poznan.pl/stash/scm/eosc-rs/rs-facade flake8:
        commands:
        - /usr/bin/env sh .sqa/script.wiggy-aquamarine-vole.sh
        container: qc.sty_geeky-azure-tzu
      git.man.poznan.pl/stash/scm/eosc-rs/rs-facade hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.squeaky-ecru-bonobo.sh
        container: qc.sty_hazy-heliotrope-coati
      git.man.poznan.pl/stash/scm/eosc-rs/rs-facade jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.breezy-saffron-balinese.sh
        container: qc.sty_shabby-goldenrod-bird
  QC.Ver:
    repos:
      git.man.poznan.pl/stash/scm/eosc-rs/rs-facade get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.stinky-buff-gecko.sh
        container: qc.ver_hazy-cinnamon-octopus
timeout: 5400
